name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: [PvPHubLLC/8]
#assignees:
#  - octocat
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Duplicate Issue Check
      options:
        - label: I have checked that an issue similar to this is not already open already!
          required: true
  - type: markdown
    attributes:
      value: "# Server Information"
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Briefly tell us what happened
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: servers
    attributes:
      label: What server(s) are you seeing the problem on?
      multiple: true
      options:
        - Practice
        - Events
        - Duels
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe steps to reproduce.
      placeholder: 1. Start typing...
      value: "1. "
  - type: markdown
    attributes:
      value: "# Client Information"
  - type: dropdown
    id: client_brand
    attributes:
      label: Client Brand
      description: What client were you running?
      options:
        - Vanilla
        - Feather Client
        - Lunar Client
        - Other (Please specify in steps to reproduce section)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: client_version
    attributes:
      label: Client Version
      description: What version of Minecraft are you running?
      options:
        - Older than 1.19.4
        - 1.19.4
        - 1.20
        - 1.20.1
        - 1.20.2
        - 1.20.3
        - 1.20.4
        - 1.21
        - 1.21.1
        - 1.21.2
        - 1.21.3
        - 1.21.4
        - Other (Please specify in steps to reproduce section)
      default: 8
    validations:
      required: true
